blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name='post_detail'),
    path('<slug:slug>/', views.category, name='category_detail'),
]

crashblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap

from .sitemaps import CategorySitemap, PostSitemap

from django.contrib import admin
from django.urls import path, include
from core.views import frontpage, about, robots_txt

sitemaps = {'category': CategorySitemap, 'post': PostSitemap}


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt', robots_txt, name='robots.txt'),
    path('admin/', admin.site.urls),
    path('about/', about, name='about'),
    path('', include('blog.urls')),
    path('', frontpage, name='frontpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return '/%s' % self.slug

class Post(models.Model):
    ACTIVE  = 'active'
    DRAFT = 'draft'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DRAFT, 'Draft')
    )
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    intro = models.TextField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return '/%s/%s' % (self.category.slug ,self.slug)

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete = models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 

core/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Category
from .forms import CommentForm

# Create your views here.
def detail(request, category_slug, slug):
    post = get_object_or_404(Post, slug=slug, status=Post.ACTIVE)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            return render(request, 'blog/detail.html', {'post': post, 'form': form})

    else:
        form = CommentForm()

    form = CommentForm()

    return render(request, 'blog/detail.html', {'post': post, 'form': form})

def category (request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.filter(status=Post.ACTIVE)
    return render(request, 'blog/category.html', {'category': category, 'posts': posts})

def search(request):
    query = request.GET.get('query', '')

    posts = Post.objects.filter(status=Post.ACTIVE).filter(Q(title__icontains=query) | Q(intro__icontains=query) | Q(body__icontains=query))

    return render(request, 'blog/search.html', {'posts': posts, 'query': query})

core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from blog.models import Post


# Create your views here.
def frontpage(request):
    posts = Post.objects.filter(status=Post.ACTIVE)
    return render(request, 'core/frontpage.html', {'posts': posts})

def about(request):
    return render(request, 'core/about.html')

def robots_txt(request):
    text = [
        "User-Agent: *",
        "Disallow: /admin/",
    ]

    return HttpResponse("\n".join(text), content_type="text/plain")

blog/templates/blog/category.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ category.title }} | {% endblock %}

{% block content %}
    <div class="header-title">
        <h2>Welcome to AllTopia!</h2>
    </div>
    <div class="blog-categories">
        <div class="blog-category cat-active">
            <p>View All</p>
        </div>
        <div class="blog-category">
            <p>Technology</p>
        </div>
        <div class="blog-category">
            <p>Lifestyle</p>
        </div>
        <div class="blog-category">
            <p>Travel</p>
        </div>
        <div class="blog-category">
            <p>Movies</p>
        </div>
        <div class="blog-category">
            <p>Music</p>
        </div>
    </div>
    <hr class="cat-post-divider">
    <!-- <p class="latest-post-tag">Latest Post</p>
    <div class="latest-post-container">
        <div class="latest-large">
            <div class="latest-l-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Lifestyle</p>
                </div>
            </div>
        </div>
        <div class="latest-small">
            <div class="latest-s-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Travel</p>
                </div>
            </div>
        </div>
    </div> -->
    <div class="main-parent-flex-container">
        {% for post in posts %}
            <div class="child-content">
                <!-- <h2 class="date-style">{{ post.created_at|timesince }} ago</h2> -->
                <a href="{% url 'post_detail' post.category.slug post.slug %}">
                    {% if post.image %}
                        <div class="blog-post-image" style="background-image: url('{{ post.image.url }}');"></div>
                    {% endif %}
                    <p class="preview-tag-p"><a href="{% url 'category_detail' post.category.slug %}" class="preview-tag">{{post.category}} </a></p>
                    <h1 class="blogs-title">{{ post.title }}</h1>
                    <p class="blogs-intro">{{ post.intro }}</p>
                    <div class="date-posted">
                        <!-- {{ post.created_at|date:'M d, Y' }} at {{ post.created_at|date:'g:i A' }} -->
                        <p><strong>{{ post.created_at|date:'M d, Y' }}</strong> at {{ post.created_at|date:'g:i A' }}</p>
                    </div>
                </a>
            </div>
            {% empty %}
                <div></div>
                <div class="empty-post">
                    <img src="../../static/assets/feeling_blue-removebg-preview.png" />
                    <p>So empty...</p>
                    <p>Oh no! There are no posts in this category.</p>
                </div>
                <div></div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ post.title }} | {% endblock %}

{% block content %}
<!-- <h1>{{ post.title }}</h1> -->
<div class="post-view-main-container">
    <div class="view-post-category-tag">
        <p class=""><strong>Posted on </strong><u><span class="post-view-date">{{ post.created_at|date:'M d, Y' }} at {{ post.created_at|date:'g:i A' }}</span></u></p>
        <p class="tag"><a href="{% url 'category_detail' post.category.slug %}" class="post-category-tag">{{post.category}} <!--<strong>Travel</strong>--></a></p>
    </div>
    <!-- <div class="post-img"></div> -->
    {% if post.image %}
        <div class="post-img" style="background-image: url('{{ post.image.url }}');"></div>
    {% endif %}
    <div class="post-view-content-container">
        <h2 class="">{{ post.title }}</h2>
        <p class="post-view-intro">{{ post.intro }} Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <hr>
        <p class="post-view-content">{{ post.body }}</p>
        <hr>
    </div>
    <div class="comment-section-container">
        <div class="comment-section-header">
            <div class="comsec-fields-container">
                    <form method="POST" class="comment-form">
                        <p class="comment-header">Join the conversation!</p>
                        <p class="comment-sub-header">Become part of the discussion by entering your name, email, and your comment below.</p>
                        <hr>
                        <br>
                        {% csrf_token %}
                        <div class="field-group">
                            <label for="id_name">Name</label>
                            {{ form.name }}
                        </div>
                        <div class="field-group">
                            <label for="id_email">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="field-group">
                            <label for="id_body">Comment</label>
                            {{ form.body }}
                        </div>
                        <button class="submit-btn">Submit comment</button>
                    </form>
                <div class="comsec-art">
                    <img src="../../static/assets/conversation.png" />
                </div>
            </div>
        </div>
        <div class="comsec-label">
            <p class="">Comments</p>
        </div>
        <div class="comments-main-container">
            {% for comment in post.comments.all %}
                <div class="comment-container">
                    <img src="../../static/assets/default-client-profile.png" class="default-account-image"/>
                        <div class="">
                            <strong>{{ comment.name }}</strong> <small>{{ comment.created_at|date:'g:i A'}}</small><br>
                            {{ comment.body }}
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}  

blog/templates/blog/search.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Search | {% endblock %}

{% block content %}
    <!-- <div class="header-title">
        <h2>Welcome to AllTopia!</h2>
    </div>
    <div class="blog-categories">
        <div class="blog-category cat-active">
            <p>View All</p>
        </div>
        <div class="blog-category">
            <p>Technology</p>
        </div>
        <div class="blog-category">
            <p>Lifestyle</p>
        </div>
        <div class="blog-category">
            <p>Travel</p>
        </div>
        <div class="blog-category">
            <p>Movies</p>
        </div>
        <div class="blog-category">
            <p>Music</p>
        </div>
    </div> -->
    <hr class="cat-post-divider">
    <!-- <p class="latest-post-tag">Latest Post</p>
    <div class="latest-post-container">
        <div class="latest-large">
            <div class="latest-l-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Lifestyle</p>
                </div>
            </div>
        </div>
        <div class="latest-small">
            <div class="latest-s-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Travel</p>
                </div>
            </div>
        </div>
    </div> -->
    <div class="search-header">
        <h1>Showing search results for</h1>
        <h3>"{{ query }}"</h3>
    </div>
    <div class="main-parent-flex-container">
        {% for post in posts %}
            <div class="child-content">
                <!-- <h2 class="date-style">{{ post.created_at|timesince }} ago</h2> -->
                <a href="{% url 'post_detail' post.category.slug post.slug %}">
                    {% if post.image %}
                        <div class="blog-post-image" style="background-image: url('{{ post.image.url }}');"></div>
                    {% endif %}
                    <p class="preview-tag-p"><a href="{% url 'category_detail' post.category.slug %}" class="preview-tag">{{post.category}} </a></p>
                    <h1 class="blogs-title">{{ post.title }}</h1>
                    <p class="blogs-intro">{{ post.intro }}</p>
                    <div class="date-posted">
                        <!-- {{ post.created_at|date:'M d, Y' }} at {{ post.created_at|date:'g:i A' }} -->
                        <p><strong>{{ post.created_at|date:'M d, Y' }}</strong> at {{ post.created_at|date:'g:i A' }}</p>
                    </div>
                </a>
            </div>
            {% empty %}
                <div></div>
                <div class="empty-post">
                    <img src="../../static/assets/undraw_Location_search-removebg.png" >
                    <p>Seems quiet around here~</p>
                    <p>Looks like we're exploring uncharted territory! No posts found in this corner of the universe.</p>
                </div>
                <div></div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}About | {% endblock %}

{% block content %}
    <!-- <link rel="stylesheet" href="{% static 'styles.css' %}"> -->
    <div class="about-main-container">
        <div class="about-parent-flex-container">
            <p>About</p>
        </div>
    </div>
{% endblock %}

core/templates/core/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Home | {% endblock %}  Crash Blog</title>
</head>
<body>
    <div class="navbar-container">
        <nav id="navbar">
            <img src="../../static/assets/alltopia_logo_nobg.png" class="logo" alt="AllTopia Logo"/>
            <!-- <h2 class="logo">
                AllTopia
            </h2> -->
            <div class="search-container">
                <span class="icon is-left">
                    <i class="fa fa-search" style="color: #CB3737;"></i>
                </span>
                <form method="get" action="{% url 'search' %}" class="search-form">
                    <input class="search-menu" name="query" type="text" placeholder="Search">
                </form>
            </div>
            <ul>
                <li class="nav-texts"><a class="nav-option" href="{% url 'about' %}"> <span class="text-hover-effect"><b>About</b></span></a></li>
                <li class="nav-texts"><a class="nav-option" href="/"> <b>Home</b> </a></li>
                <li>
                </li>
            </ul>
        </nav>
    </div>
    <section class="blogs-list" id="blogs">
        {% block content %}
        {% endblock %}
    </section>
    <footer>
        <div class="footer-main-container">
            <div class="footer-contents">
                <p>Copyright (c) 2024 - AllTopia.</p>
            </div>
        </div>
    </footer>
</body>
</html>

<!-- http://127.0.0.1:8000/ -->

core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="header-title">
        <h2>Welcome to AllTopia!</h2>
    </div>
    <div class="blog-categories">
        <div class="blog-category cat-active">
            <p>View All</p>
        </div>
        <div class="blog-category">
            <p>Technology</p>
        </div>
        <div class="blog-category">
            <p>Lifestyle</p>
        </div>
        <div class="blog-category">
            <p>Travel</p>
        </div>
        <div class="blog-category">
            <p>Movies</p>
        </div>
        <div class="blog-category">
            <p>Music</p>
        </div>
    </div>
    <hr class="cat-post-divider">
    <p class="latest-post-tag">Latest Post</p>
    <div class="latest-post-container">
        <div class="latest-large">
            <div class="latest-l-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Lifestyle</p>
                </div>
            </div>
        </div>
        <div class="latest-small">
            <div class="latest-s-img"></div>
            <div>
                <h3 class="latest-blog-l-title">Lorem Ipsum dolor amet.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            </div>
            <div class="post-info-row">
                <div class="date-posted">
                    <p><strong>Mar 19, 2022</strong> at 10:25 PM</p>
                </div>
                <div class="post-category-tag">
                    <p>Travel</p>
                </div>
            </div>
        </div>
    </div>
    <div class="main-parent-flex-container">
        {% for post in posts %}
            <div class="child-content">
                <!-- <h2 class="date-style">{{ post.created_at|timesince }} ago</h2> -->
                <a href="{% url 'post_detail' post.category.slug post.slug %}">
                    {% if post.image %}
                        <div class="blog-post-image" style="background-image: url('{{ post.image.url }}');"></div>
                    {% endif %}
                    <p class="preview-tag-p"><a href="{% url 'category_detail' post.category.slug %}" class="preview-tag">{{post.category}} </a></p>
                    <h1 class="blogs-title">{{ post.title }}</h1>
                    <p class="blogs-intro">{{ post.intro }}</p>
                    <div class="date-posted">
                        <!-- {{ post.created_at|date:'M d, Y' }} at {{ post.created_at|date:'g:i A' }} -->
                        <p><strong>{{ post.created_at|date:'M d, Y' }}</strong> at {{ post.created_at|date:'g:i A' }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}